package com.waynabox.springpoc.booking.domain.service;

import org.apache.commons.lang3.exception.ExceptionUtils;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Logger;

/**
 * calls booking dates
 */
public class BookingConnection {

    private final static Logger log = Logger.getLogger(BookingConnection.class.getName());

    protected final static String URL_CALL = "https://waynabox.com/es/api/packs?departureId=%s&days=%s";

    protected final static int[] AVAILABLE_DAYS = {3, 5};
    protected final static int[] AVAILABLE_DEPARTURE_IDS = {3, 13, 15, 16, 29, 31, 64};

    public String urlComposer(final String urlTemplate, final int departureId, final int day ) {
        return String.format(urlTemplate, departureId, day);
    }

    protected String makeCall(final int departureId, final int days) {
        try {

            URL url = new URL(urlComposer(URL_CALL, departureId, days));
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Accept", "application/json");

            if (connection.getResponseCode() != 200) {
                throw new RuntimeException("Failed: HTTP error code: " + connection.getResponseCode());
            }

            BufferedReader br = new BufferedReader(new InputStreamReader(connection.getInputStream()));

            log.info("Output generated by server...");
            String output = org.apache.commons.io.IOUtils.toString(br);
            log.info(output);

            connection.disconnect();
            return output;

        } catch (IOException e) {
            log.severe(ExceptionUtils.getStackTrace(e));
        }
        return "";
    }
}
